### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by murrellb** [MurrellGroup/InvariantPointAttention.jl#3]
- [ ] Testing. Compare with other implementations, and add tests to ensure correctness is maintained.
- [x] Remove regular IPA. For code maintenance purposes, normal IPA should be a call to cross-attention, just passing the same inputs twice.
- [ ] Clean up rigid body transformations to bring in line with other codebases (this includes tweaking Diffusions.jl)
